### ISSUE TITLE
common metrics not on maven central

### ISSUE THREAD

**Issue by fommil** [twitter/commons#348]
com.twitter.common#metrics;0.0.29 is not available no maven central.

This means that much of finagle cannot be used without adding additional maven repositories: banned in many corporate environments.

**Comment by Yasumoto** [comment]
@stuhood is this related to the work you were doing earlier? (aka #346 )

**Comment by fommil** [comment]
Still not on maven central. Can you please add this to central, as it is a dependency of finagle which is distributed on central.

**Comment by jsirois** [comment]
Noting that pants just gained the last bits [1] needed to properly support maven central publishing, so in the next upgrade of twitter/commons to pantsbuild.pants [2] >= 0.0.33 (not published to pypi yet) I'll enable maven-central publishing for the repo.

With that done I'll hand this issue back to a tweep to actually do the publish.  Twitter has an internal publishing / consumption scheme that may or may not still include maven.twttr.com and it should be ensured that the metrcis artifact is only published to one public repo for sanity sake.

[1] https://rbcommons.com/s/twitter/r/2184/
[2] https://pypi.python.org/pypi/pantsbuild.pants/0.0.32

**Comment by codeape** [comment]
Any update on this? This makes finagle and finatra unusable.

**Comment by jsirois** [comment]
All the pants (build-tool) work is done and commons is upgraded to a version that supports maven-central publishing (pantsbuild.pants itself uses this to publish its [own jars](http://search.maven.org/#search%7Cga%7C1%7Corg.pantsbuild)).  The rest is policy / technicality issues for a Tweep to wrangle.  I'll pass this off to @stevegury to start with since he's an actual tweep and he's been involved in both finagle and metrics.  Steve - let me know if you need any pointers on maven-central publishing setup if you get to the point where you want to publish this from github.  I assume though that the publish will be done from within Twitter using their sync of this code.

**Comment by stevegury** [comment]
Correction, I *was* an actual tweep.
I defer to @kevinoliver @vkostyukov @luciferous

**Comment by kevinoliver** [comment]
We'll try to take a look into making this happen.

**Comment by glasser** [comment]
maven.twttr.com has been down for over a day (returning 503s consistently). Would it be possible to publish to somewhere else?

**Comment by kevinoliver** [comment]
@glasser someone took a look and fixed that. i agree it would be nice if these were published on maven central.

**Comment by glasser** [comment]
Thanks! Great to see it up again.
