### ISSUE TITLE
JMX exposure of metrics

### ISSUE THREAD

**Issue by schrepfler** [twitter/commons#399]
Some places are pretty adamant having metrics exposed as JMX, can common metrics be exposed over JMX via some configuration (if so how, the documentation does not seem to mention it)?

**Comment by jsirois** [comment]
Nope - not today.  I don't believe Twitter uses jmx, so your best bet would be to write an https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/metrics/MetricListener.java in a non-Twitter repo that takes metric update notifications and exports them to a JMX model.  If you can share that work so others can leverage it - all the better.  If patches are needed to commons metrics to support your JMX exporter, those patches would be appropriate to land here.

In case you're not aware - take a look at: https://github.com/twitter/commons/blob/master/CONTRIBUTING.md

**Comment by schrepfler** [comment]
Thanks, I've noticed some similarity between the twitter commons metrics and the codahale metrics library, do you think some inspiration can be taken from its JMXReporter?

**Comment by jsirois** [comment]
Yes.  That looks like it uses all the same concepts.

**Comment by schrepfler** [comment]
Is there any reason why Gauge, Counter and HistogramInterface don't extend a common Metric interface (just having a name attribute is a weak commonality but still)?

**Comment by jsirois** [comment]
I suspect just because there was no need for this (yet).  Do you need this ultimately because MetricListener only presents a stat snapshot with the stat source type info squashed out (you just get string metric name keys)?

**Comment by schrepfler** [comment]
I'm experimenting in shoving something similar to a codahale JmxReporter into your library and his library uses this abstraction, but it's not that relevant, just exploring your API design.

**Comment by jsirois** [comment]
Got it.  Do note I'm not really a good representative here.  Although I did work at Twitter and review (and write a tiny bit) of the metrics (and stats) packages I no longer work at Twitter and mainly have twitter github org access to perform pants upgrades on this repo.  Before you get too far down the road you should grab the attention of @stevegury and @wfarner who did most of the coding and can at least direct you to a more current maintainer if they are not it.

**Comment by wfarner** [comment]
Sorry to pass the buck, i haven't walked these halls for a few years.  Though Steve may indeed be a better target.

However, i'm sorry to say that in my opinion twitter commons code is not a great candidate for direct consumption, and you might be better off looking at alternatives.  These libraries are ostensibly open source because other first-class open source projects rely on them.

**Comment by schrepfler** [comment]
For reference, this project https://github.com/rlazoti/finagle-metrics exposes twitter commons metrics to dropwizard metrics.

**Comment by jsirois** [comment]
So - to put a finer point on @schrepfler 's implied context here - c.t.common.metrics must be considered effectively 1st class (even though it isn't right now as Bil;l correctly points out), since finagle - which is 1st class - uses it.  CC @kevinoliver who has some form of maintainership role as indicated by activity on #348 today

**Comment by jsirois** [comment]
That last may in fact be incorrect, since finagle uses a different abstraction with a metrics adapter, in which case https://github.com/rlazoti/finagle-metrics would cover the 1st class api and be potentially backed by the commons metrics jar as the impl.

Sorry for injecting confusion.  I think Bill's point stands.

**Comment by schrepfler** [comment]
Looking at the code https://github.com/rlazoti/finagle-metrics/blob/master/src/main/scala/com/twitter/finagle/metrics/MetricsStatsReceiver.scala (really, that's it) finagle-metrics looks to be integrating with the finagle code only thus my original statement is incorrect, finagle metrics get bridged over to dropwizard metrics. This bridge is not adequate to expose twitter-common metrics. Sorry for any confusion that it might have introduced.
